sudo: false
language: python
python:
 - 2.7
 - 3.6
 - 3.7
 - 3.8
install:
 - pip install -r requirements-dev.txt
 - python setup.py develop
script: py.test --cov pyramid_skosprovider --cov-report term-missing
after_success: coveralls
