language: python
python:
 - 2.7
 - 3.3
 - 3.4
install:
 - python setup.py develop
 - pip install -r requirements-dev.txt
script: py.test --cov pyramid_skosprovider --cov-report term-missing
after_success: coveralls
